Shelter post detail 로직 구현
prgrms-web-devcourse/Team_i6_comepet_FE pull request #133
Opened 2021-12-20 07:56 UTC by Jihyeon228

## 이슈 번호 

- close: #132

## 특이 사항

### 구현 내용
- 조회
- 북마크 저장, 삭제

2021-12-20 11:45 UTC, ghost requested changes
![image](https://user-images.githubusercontent.com/81365896/146762411-aad6ddf3-c3e0-47d3-8e50-4a143de45038.png)

에러 해결 부탁드립니다.

2021-12-20 11:46 UTC, sanoopark commented on src/views/Post/ShelterPostDetailPage/ShelterPostDetailPage.jsx
> +      await axios.post(`shelter-posts/${id}/bookmark`).catch(function (error) {
`POST`를 사용해주세요

2021-12-20 11:47 UTC, sanoopark commented on src/views/Post/ShelterPostDetailPage/ShelterPostDetailPage.jsx
> +  };
북마크 동작이 안 되는데 확인 부탁드립니다

2021-12-20 15:46 UTC, wherehows commented on src/views/Post/ShelterPostDetailPage/ShelterPostDetailPage.jsx
> +  const [isBookmarkOn, setIsBookmarkOn] = useState(null);
일전에 이야기 나눈대로 data를 받아오지 못하는 경우, 아래와 같은 코드로 방어 코드 만들어 줄 수 있을 것 같습니다.

if(!data) return <div></div>

추후 로딩 처리는 필요하겠지만요.

2021-12-20 17:53 UTC, sanoopark requested changes
https://user-images.githubusercontent.com/81365896/146810848-dce920ac-991a-402d-84d3-c7678b35e2d8.mov

확인 부탁드립니다!

2021-12-21 07:34 UTC, wherehows approved these changes

2021-12-21 08:10 UTC, merged