Refactor: Feat: LongHeader 마크업 추가
prgrms-web-devcourse/Team_i6_comepet_FE pull request #28
Opened 2021-12-03 06:31 UTC by wherehows

## 이슈 번호 

- close: #26 

## 특이 사항

### 돋보기 ICON 배치에 관하여
- INPUT 태그의 가운데에 배치하는 방법이 깔끔하진 않습니다. 오른쪽과 위쪽에 적당한 margin을 줘서 배치했는데요. 혹시 다른 방법이 있으신 분이 계시다면 코멘트 부탁 드립니다.  position 속성 때문에 flex로 가운데 배치하기가 불가능해요

2021-12-04 06:15 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
> +                margin="0 5rem 0 0"
Image 컴포넌트에 margin prop이 없기 때문에 적용이 안 되고 있습니다.

```suggestion
```

2021-12-04 06:16 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
> +              실종 및 보호
Image 컴포넌트에 margin prop이 없기 때문에 적용이 안 되고 있습니다.
```suggestion
             <ButtonText>실종 및 보호</ButtonText>
```

2021-12-04 06:19 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
> +
```suggestion
const ButtonText = styled.div`
  margin: 0.3rem 0 0 0.5rem;
`;
```
Button 안에서 Image는 수직정렬 됐지만 텍스트는 수직정렬 되지 않아 생긴 문제로 Image에 margin을 주지 않고 div에 margin을 줬습니다. 

적용 결과입니다.
![image](https://user-images.githubusercontent.com/81365896/144699917-cc7c20e9-3236-47a7-aba0-24e0f6e44345.png)

2021-12-04 06:21 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
> +              bgColor="#fff"
앨리스가 Button의 bgColor로 "normalWhite" 문자열을 주는 형태로 Button 컴포넌트를 수정해서 진행 중이라 에드워드도 이 부분 먼저 수정해주시면 좋을 것 같습니다!

2021-12-04 06:23 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
> +          <h1>Comepet</h1>
브랜드 컬러가 적용 안 되어 있습니다

![image](https://user-images.githubusercontent.com/81365896/144700027-441662b6-c0b3-4ae2-bef9-7b366dc15fad.png)

2021-12-04 06:28 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
> +import { Input } from '@/components/Input';
![image](https://user-images.githubusercontent.com/81365896/144700120-1763b36e-07df-4505-a634-7faa23b82861.png)
![image](https://user-images.githubusercontent.com/81365896/144700149-35eb1c42-c096-470b-89d9-fda76303ca94.png)


![image](https://user-images.githubusercontent.com/81365896/144700137-a4248078-d131-4279-98e2-c3558d6b384a.png)

Input의 placeholder font-weight가 bold로 정해져 있습니다. 피그마 디자인대로 normal로 수정하면 좋을 것 같습니다

2021-12-04 06:40 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
> +          <StyledSearch />
Input의 Icon 수직 정렬에 대한 해결법입니다.

```suggestion
          <InputWrapper>
            <Input placeholder="세부 검색을 위해 클릭해주세요" borderRadius="1.6rem" />
            <StyledSearch />
          </InputWrapper>
```

2021-12-04 06:42 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
> +  color: ${({ theme }) => theme.colors.brand};
Input의 Icon 수직 정렬에 대한 해결법입니다.

```suggestion
  position: absolute;
  top: 50%;
  right: 2%;
  transform: translateY(-50%);
  font-size: 3rem;
  color: ${({ theme }) => theme.colors.brand};
```
![image](https://user-images.githubusercontent.com/81365896/144700447-fdb1a189-5ad2-41b8-bb8e-b98bc0687d16.png)

2021-12-04 06:42 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
> +
Input의 Icon 수직 정렬에 대한 해결법입니다.

```suggestion
const InputWrapper = styled.div`
  position: relative;
  width: 100%;
`;
```

2021-12-04 06:57 UTC, sanoopark requested changes
분량이 많아서 일단 보이는 것들 위주로 리뷰 드렸습니다!

그리고 mui에서 가져오는 Icon들은 좀 길더라도 명시적으로 <Styled ... Icon> 으로 하는 건 어떨까요?

2021-12-04 12:12 UTC, wherehows commented on src/components/Header/LongHeader.jsx
> +
Button 에 display flex를 통해서 수직 정렬 된 것으로 보이는데, 혹시 수직 정렬이 안돼 보였을까요?

지금 확인하는데 위에 제시해주신 코드 없이도 수직 정렬이 잘 된 것으로 보여서요!

![image](https://user-images.githubusercontent.com/81841082/144708964-1dc850f7-d741-40da-8629-4b2893420ece.png)

2021-12-04 22:05 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
> +
f08f3db 기준으로 이렇게 보이네요

https://user-images.githubusercontent.com/81365896/144725975-907a7599-b23a-4d9c-a33b-bb46decd3300.mov

2021-12-06 05:34 UTC, sanoopark approved these changes

2021-12-06 06:41 UTC, merged