Refactor: LongHeader 및 ShortHeader 통합
prgrms-web-devcourse/Team_i6_comepet_FE pull request #48
Opened 2021-12-07 04:51 UTC by wherehows

## 이슈 번호 

- close: #47 

## 특이 사항
### mui Popper Library 사용과 관련한 에러
- 현재 Popper를 사용하면 아래와 같은 에러가 발생합니다.
![image](https://user-images.githubusercontent.com/81841082/144967401-63bad97c-1a23-4794-8c72-e5b625fd2ee1.png)
- 제거하는 방법은 ThemeProvider의 shadows 프로퍼티 내에 1이라는 프로퍼티 이름에 shadow값을 할당하면 되긴 합니다만, 굳이 이렇게 해야하나 싶어서 냅뒀습니다.
- 추가적으로, Library를 사용함으로써 저희가 얻고 있는 기능은 단순히 모달 창이 천천히 켜지고 천천히 꺼지는, 애니메이션 효과에 불과한데요. 굳이 Library를 써야 하나 싶습니다. Popper과 Button이 하나의 컴포넌트 안에 존재해야 하기 때문에, 태그명도 굉장히 불확실합니다.
 가령, MenuButton으로 이름을 지어서 사용하고 있는데, 실제로 Sidebar Modal 역시도 MenuButton 컴포넌트 안에 구현이 돼있어야 하는 상황이 그렇습니다(아래 코드 참조). 어제 MenuButton과 onClick을 하는 경우 모달 창이 보여지게끔 분리하는 코드를 생각해봤는데, 마땅한 방법이 안 떠오르더라고요.
 혹여나 나머지 분들께서 동의하신다면 라이브러리를 걷어내겠습니다.
![image](https://user-images.githubusercontent.com/81841082/144968499-52562788-8ea7-41ed-9530-805e0ece107d.png)

2021-12-07 08:46 UTC, Jihyeon228 commented on src/components/Header/LongHeader.jsx
>              <IconContainer>
Line 36: 로그인 안 했을 때는 기본 프로필 아이콘으로 바꿔주세요.

2021-12-07 12:52 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
>  `;
![스크린샷 2021-12-07 오후 9 45 43](https://user-images.githubusercontent.com/81365896/145031693-b77a9b4c-92fb-4a16-9f83-808cb74b6e68.png)

![image](https://user-images.githubusercontent.com/81365896/145032246-81b1117d-e3f7-497a-a883-d8d24a8152ed.png)

Header 안에 padding을 주면 어떨까요?

2021-12-07 12:58 UTC, sanoopark commented
![image](https://user-images.githubusercontent.com/81365896/145033077-381854f2-21d8-4f20-9857-68d83dad6e3b.png)

![image](https://user-images.githubusercontent.com/81365896/145033133-6eb47d84-2cdc-4286-956a-ee21e51d09d9.png)

컨벤션 대로 파일명 바꿔주시고 export하는 index.js를 각 폴더에 추가해주시면 감사하겠습니다

2021-12-07 12:59 UTC, sanoopark commented on src/components/Header/NotificationButton/index.jsx
> +                  <TextWrapper>전체삭제</TextWrapper>
![image](https://user-images.githubusercontent.com/81365896/145033483-f5567289-4d34-4397-ad9f-cb6fbcc4a94c.png)

모바일인데 크기가 많이 작은 것 같고, 시맨틱을 위해 Button이 들어가면 좋을 것 같아요

2021-12-07 13:02 UTC, ghost commented on src/components/Header/NotificationButton/index.jsx
> +                    color="normalBlack">
```suggestion
                    type="button"
                    height="100%"
                    bgColor="lighterGray"
                    borderRadius="0 0 1rem 1rem"
                    color="normalBlack">
```

2021-12-07 13:04 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
>            <StyledHeader>Comepet</StyledHeader>
![image](https://user-images.githubusercontent.com/81365896/145034201-fb64d4b5-5d59-49d2-8b4b-c5350a08e27d.png)

가운데 정렬이 고정값으로 들어가 있어서 반응형에서 가운데 정렬이 안 되고 있습니다

2021-12-07 13:05 UTC, sanoopark commented on src/components/Header/Modal/NotificationModal/index.jsx
> +                  <Seperator type="horizon" key={index} />
```suggestion
                <li key={index}>
                  <Seperator type="horizon" />
```
wrapper에 key가 들어가야 합니다

2021-12-07 13:08 UTC, sanoopark commented on src/components/Header/Modal/index.jsx
> +export default Modal;
구조상 NotificationModal과 SidebarModal만을 위한 컴포넌트인 것 같은데 그렇다면 HeaderModal로 네이밍하는 게 좋을 것 같습니다

2021-12-07 13:17 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
>          <TopContainer>
Container는 `IconContainer`처럼 비슷한 종류를 묶는 느낌이라 TopWrapper, MiddleWrapper, BottomWrapper로 분류하면 어떨까요?
```
Wrapper
ㄴ TopWrapper
ㄴ MiddleWrapper
ㄴ BottomWrapper
```

2021-12-07 13:22 UTC, wherehows commented on src/components/Header/LongHeader.jsx
>          <TopContainer>
IconContainer는, 비슷한 종류를 묶는다기 보단, 마땅한 명칭이 없고, 2개 이상의 태그가 묶이기 때문에 IconContainer라고 명명했습니당.

일전에 2개 이상의 태그가 들어가는 경우 Container suffix를 붙이기로 했는데 제시해준 방향대로라면 바뀌는걸로 생각하면 될까용?

2021-12-07 13:22 UTC, ghost commented on src/components/Header/SidebarButton/index.js
> +export default MenuButton;
컴포넌트명은 MenuButton인데 `SidebarButton/index.js` 이름이 다릅니다

2021-12-07 13:39 UTC, wherehows commented on src/components/Header/LongHeader.jsx
>            <StyledHeader>Comepet</StyledHeader>
아래와 같이 가운데 정렬을 하긴 했습니다만, 아이콘이랑 수직 정렬이 미세하게 틀어지네요.
저번에 찾아본다고 들었었는데 혹시 알아낸거 있으신가용?

```
position: absolute;
left: 50%;
transform: translateX(-50%);
```

2021-12-07 13:46 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
>          <TopContainer>
네 맞아요 그렇기는 한데 엘리먼트가 2개 이상이면 Container, 1개면 Wrapper로 명명하는 기준을 둔다면 Container로 바꿔야 할 Wrapper가 꽤 있는 것 같아서요. 아래는 제가 스크랩한 건데 중간에 `contains all the rest of HTML element`, `aligned all our main content`를 보면 큰 덩어리를 감싸는 뉘앙스라 고민이 되네요

![image](https://user-images.githubusercontent.com/81365896/145039085-a537d3fa-b9dc-48dd-85fd-16c14764db1f.png)

2021-12-07 13:52 UTC, wherehows commented on src/components/Header/Modal/index.jsx
> +export default Modal;
Header 폴더 내부적으로만 존재하는 컴포넌트인데 HeaderModal을 또 붙여주어야 할까요?

2021-12-07 13:54 UTC, wherehows commented on src/components/Header/Modal/index.jsx
> +export default Modal;
HeaderModal로 변경하게되면, 폴더 네임도 따라가야 하지 않나 싶습니다. 만약 따라가게 된다면 Header폴더 안에 HeaderModal 폴더 안에 NotificationModal과 SidebarModal이 있게 되는건데, Header 폴더안에 Modal안에 NotificationModal과 SidebarModal이 있다. 의 흐름이 더 깔끔하지 않을까용?
![image](https://user-images.githubusercontent.com/81841082/145041794-993d9621-50d3-40a8-91c9-b6362831b0cc.png)

2021-12-08 06:02 UTC, wherehows commented on src/components/Header/LongHeader.jsx
>          <TopContainer>
구두로 이야기한대로,

Container는 Redux에서 나오는 Container와의 혼동이 있을 수 있으니, 단순히 디자인적인 요소로 감싸는 경우는 모두 Wrapper로 통일하겠습니다.

2021-12-08 06:04 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
>          <TopContainer>
회의 기록
- Container는 리덕스의 Presentational Component와 혼동될 수 있음
- 리덕스를 사용하진 않지만 별개의 기능을 담는 뉘앙스를 갖고 있다면 피하는 것도 좋다는 판단
- Wrapper나 Container나 스타일을 위한 div의 역할 뿐이므로 Wrapper로 통일하기로 결정

2021-12-09 05:43 UTC, Jihyeon228 commented on public/images/profile-image-loggedout.svg
> +<path d="M26.749 24.93C28.1851 23.2021 29.184 21.1537 29.661 18.9582C30.1381 16.7626 30.0793 14.4845 29.4897 12.3164C28.9001 10.1484 27.797 8.15423 26.2737 6.50268C24.7504 4.85112 22.8517 3.59075 20.
Mui의 AccountCircleIcon 을 안쓰고 svg 파일 넣은 이유가 있으신가요?

2021-12-09 06:58 UTC, sanoopark requested changes
### 피그마 디자인
![image](https://user-images.githubusercontent.com/81365896/145347967-3fe9ecdd-03f4-405e-896b-22b6e9b945a6.png)

### 변경 필요
![image](https://user-images.githubusercontent.com/81365896/145348357-2e72bbd6-19f4-45b7-b018-833ff354d67b.png)

- TopWrapper padding-top 1.8rem
- TopWrapper 아이콘 끝선에 맞춰 정렬
- TopWrapper 로고 2.5rem bold
- TopWrapper 알림 아이콘 빨간색 notification
- BottomWrapper Input 끝선에 맞춰 width 증가
- BottomWrapper 검색 아이콘 원형에 bgColor brand

2021-12-09 07:26 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
>            <BackgroundBox width="15rem" boxShadow="0px 4px 16px rgba(0, 0, 0, 0.08)">
```suggestion
          <BackgroundBox width="45%" boxShadow="0px 4px 16px rgba(0, 0, 0, 0.08)">
```

2021-12-09 07:28 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
> +  cursor: pointer;
```suggestion
  position: absolute;
  left: 50%;
  transform: translateX(-50%);
  display: flex;
  align-items: center;
  height: 5.1rem;
  margin: 0;
  font-size: 2.5rem;
  color: ${({ theme }) => theme.colors.brand};
  cursor: pointer;
```

2021-12-09 07:28 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
>    margin-top: 0.8rem;
```suggestion
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 0.8rem;
  padding: 0 2.4rem;
```

2021-12-09 07:29 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
>    margin: 1.6rem 2.8rem 0 2.8rem;
```suggestion
  margin: 1.6rem 2.4rem 0 2.4rem;
```

2021-12-09 07:29 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
> +  padding: 0.5rem 1rem;
```suggestion
  padding: 1rem 2.4rem;
```

2021-12-09 07:31 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
>  `;
```suggestion
  display: flex;
  align-items: center;
  height: 5.1rem;
  margin: 0;
  font-size: 2.5rem;
`;
```

2021-12-09 07:31 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
>    justify-content: space-around;
```suggestion
  justify-content: space-between;
```

2021-12-09 07:31 UTC, sanoopark commented on src/components/Header/LongHeader.jsx
>  `;
```suggestion
  padding: 0 2.4rem;
`;
```

2021-12-09 07:33 UTC, sanoopark commented
LongHeader에 수정값 코멘트 달았습니다~!

https://user-images.githubusercontent.com/81365896/145353370-b6fcc1a6-0763-4064-8ab2-e13d275568a3.mov

2021-12-09 07:42 UTC, Jihyeon228 commented on src/components/Seperator/Seperator.jsx
> +  width: ${({ type }) => type === 'vertical' && '0.05rem'};
제가 width를 빼먹었나봐요, 에드워드 미안하지만 수정 부탁드려도 될까요?
```suggestion
  width: ${({ type, width }) => type === 'vertical' && '0.05rem' || width};
```

2021-12-09 07:46 UTC, wherehows commented on src/components/Seperator/Seperator.jsx
> +  width: ${({ type }) => type === 'vertical' && '0.05rem'};
아래와 같이 코드 작성했습니다.

```suggestion
  width: ${({ type, width }) => type === 'vertical' && (width || '0.05rem'});
```

2021-12-09 08:27 UTC, wherehows commented on src/components/Header/LongHeader.jsx
>  `;
이렇게 하는 경우, login 되었을 때 오른쪽 끝에 아이콘이 두 개 렌더링되는 경우(인포메이션 아이콘, 알림아이콘), 한쪽으로 치우치게 됩니다.

font-size는 반영시켜 놓겠습니다.

2021-12-09 08:47 UTC, Jihyeon228 approved these changes

2021-12-09 09:39 UTC, sanoopark approved these changes

2021-12-09 10:12 UTC, merged