Feat: PostDetailPage 마크업 추가
prgrms-web-devcourse/Team_i6_comepet_FE pull request #59
Opened 2021-12-09 07:37 UTC by wherehows

## 이슈 번호 
- close: #54 

## 특이 사항
- 디자인 자체에 대한 피드백 부탁드립니다.
- 태그는 아직 분리하지 않은 채 PostDetailPage 파일 내에 전부 구현하였습니다. 태그는 분리 예정이므로, 태그명에 대한 코드리뷰는 아직 안해주셔도 됩니다.

2021-12-09 07:48 UTC, sanoopark requested changes
> 아래 사진에 보이듯이, 맨 마지막 댓글과 댓글 작성간의 margin은 의도한게 아닙니다. ul태그의 last-child에 접근하여 margin을 제거하려 하였으나 적용되지 않아서, 현재 다른 방법을 찾고 있는 중에 있습니다. 참고 부탁 드립니다.

CommentList (ul) 의 padding-bottom을 0으로 하면 될 것 같습니다!

2021-12-09 07:49 UTC, sanoopark commented on src/views/Post/PostDetailPage/PostDetailPage.jsx
> +  padding: 1.6rem;
```suggestion
  padding: 1.6rem 1.6rem 0 1.6rem;
```

2021-12-09 07:54 UTC, sanoopark commented
![image](https://user-images.githubusercontent.com/81365896/145356057-6bb63c5f-ac2e-453a-8275-09175671b7dc.png)

댓글 input의 width를 조절해야 할 것 같습니다

2021-12-09 07:55 UTC, sanoopark commented
![image](https://user-images.githubusercontent.com/81365896/145356223-b26c7341-5331-47b6-950f-53500773188e.png)

반응형에서 공간이 충분해지면 해시태그를 한 줄로 보여주는 건 어떨까요?

2021-12-09 07:58 UTC, sanoopark commented
![image](https://user-images.githubusercontent.com/81365896/145356629-c44fb08b-94f8-4704-a9dc-eefab17c8082.png)

ScrapCounter의 medium 크기가 생각보다 작아서 수정이 필요할 것 같습니다. 이 부분은 제가 이슈에 올려놓고 수정하겠씁니다

2021-12-09 08:04 UTC, sanoopark commented
![image](https://user-images.githubusercontent.com/81365896/145357354-b231af11-284c-4565-8b9f-201a440956b7.png)

![image](https://user-images.githubusercontent.com/81365896/145357257-ae0ac3e6-447b-49d1-9bcf-42196ae0237f.png)

개인적인 생각으로 반응형을 추가할 게 아니라면 `장소`는 `word-break:keep-all`을 넣어 라벨 바로 옆에 써주는 게 자연스러운 것 같습니다.

2021-12-10 07:22 UTC, Jihyeon228 commented on src/views/Post/PostDetailPage/PostDetailPage.jsx
> +                <HashTag>#최대글자수　#최대글자수</HashTag>
해시태그는 한 줄 또는 오른쪽 여백이 많지 않게 하는 게 보기 좋을 것 같습니다.

2021-12-10 07:22 UTC, Jihyeon228 commented on src/views/Post/PostDetailPage/PostDetailPage.jsx
> +              </UserProfileWrapper>
닉네임 폰트 사이즈를 조금 줄이고 위에 마진을 줘서 아바타 높이랑 비슷하게 보여주면 더 좋을 것 같아요.

2021-12-10 11:15 UTC, wherehows commented
> ![image](https://user-images.githubusercontent.com/81365896/145356057-6bb63c5f-ac2e-453a-8275-09175671b7dc.png)
> 
> 댓글 input의 width를 조절해야 할 것 같습니다

- 추후 로직 구현시, contenteditable 적용과 함께 반영 하겠습니다.

> ![image](https://user-images.githubusercontent.com/81365896/145357354-b231af11-284c-4565-8b9f-201a440956b7.png)
> 
> ![image](https://user-images.githubusercontent.com/81365896/145357257-ae0ac3e6-447b-49d1-9bcf-42196ae0237f.png)
> 
> 개인적인 생각으로 반응형을 추가할 게 아니라면 `장소`는 `word-break:keep-all`을 넣어 라벨 바로 옆에 써주는 게 자연스러운 것 같습니다.

- 수정했습니다.




> ![image](https://user-images.githubusercontent.com/81365896/145356307-4f5e87b7-d28d-470f-8301-3c4ef9d4382f.png)
> 
> ![image](https://user-images.githubusercontent.com/81365896/145356223-b26c7341-5331-47b6-950f-53500773188e.png)
> 
> 반응형에서 공간이 충분해지면 닉네임과 조회수, 추가 메뉴 버튼을 한 줄로 보여주고, 해시태그도 한 줄로 보여주는 게 어떨까요?
> 
> 아니면 날짜와 조회수를 닉네임 밑으로 둬도 괜찮을 것 같습니다

- 데스크탑 구현시 참고하겠습니다.

2021-12-10 11:47 UTC, sanoopark approved these changes

2021-12-14 06:57 UTC, Jihyeon228 approved these changes

2021-12-15 10:19 UTC, merged