ProfileUpdatePage 마크업 추가
prgrms-web-devcourse/Team_i6_comepet_FE pull request #67
Opened 2021-12-10 09:13 UTC by Jihyeon228

## 이슈 번호 

- close: ProfileUpdatePage 마크업 추가 #58

## 특이 사항

### 나중에 Input에 label  추가 할 예정입니다.

2021-12-13 11:49 UTC, sanoopark commented
![image](https://user-images.githubusercontent.com/81365896/145806577-e5d225b0-1279-43bd-a0f1-13e4e7f2e917.png)

![image](https://user-images.githubusercontent.com/81365896/145807007-4cd69778-41b7-421d-bfcd-b13178aa1eb0.png)

배치를 이렇게 하면 어떨까요?

2021-12-13 11:50 UTC, sanoopark commented on src/components/Input/Input.jsx
> +      disabled={disabled}
disabled가 있으면 readOnly는 없어도 되는 것 같아요

2021-12-13 11:51 UTC, sanoopark commented on src/views/User/ProfileUpdatePage/ProfileUpdatePage.jsx
> +    }
테스트용인가요?

2021-12-13 11:52 UTC, sanoopark commented on src/views/User/ProfileUpdatePage/ProfileUpdatePage.jsx
> +            file: ``,
의도적으로 사용하신 벡틱인가요?

2021-12-13 11:53 UTC, sanoopark commented on src/views/User/ProfileUpdatePage/ProfileUpdatePage.jsx
> +            password2: ''
백엔드에서 passwordCheck라고 정해줘서 네이밍 변경하면 좋을 것 같습니다. 제가 한 부분에서도 변경할 계획입니다

2021-12-13 11:54 UTC, sanoopark commented on src/views/User/ProfileUpdatePage/ProfileUpdatePage.jsx
> +                  <StyledP>프로필 이미지 변경</StyledP>
어떤 목적으로 p 태그를 쓰신 걸까요?

2021-12-13 11:59 UTC, sanoopark commented on src/views/User/ProfileUpdatePage/ProfileUpdatePage.jsx
> +                    accept=".png,.jpg,.jpeg"
accept="image/*"를 안 쓰신 이유가 있을까요?

2021-12-13 12:02 UTC, sanoopark commented on src/views/User/ProfileUpdatePage/ProfileUpdatePage.jsx
> +};
utils/helpers.js 에 있는 걸 사용해주시면 됩니다!

2021-12-13 12:13 UTC, sanoopark commented on src/views/User/ProfileUpdatePage/ProfileUpdatePage.jsx
> +`;
```suggestion
const Wrapper = styled.div`
  padding: 0 2.4rem 2.4rem 2.4rem;
`;

const Form = styled.form`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  margin: 12rem 0 0 0;
`;
```

`ProfileUpdateWrapper`는 없어도 될 것 같아요. div의 기본값 (width 100%)도 활용해주시면 좋을 것 같습니다

2021-12-13 12:13 UTC, sanoopark requested changes
![image](https://user-images.githubusercontent.com/81365896/145814786-21771aa2-9133-4346-82c6-b7f358d910ec.png)
개행이 필요해요

이외 코멘트 확인 부탁드립니다!

2021-12-13 14:49 UTC, Jihyeon228 commented on src/views/User/ProfileUpdatePage/ProfileUpdatePage.jsx
> +                  <StyledP>프로필 이미지 변경</StyledP>
폰트 사이즈랑 색상 변경하려고 사용했습니다.

2021-12-13 14:49 UTC, Jihyeon228 commented on src/views/User/ProfileUpdatePage/ProfileUpdatePage.jsx
> +                    accept=".png,.jpg,.jpeg"
프리뷰로 보여줘야 돼서 많이 쓰이는 이미지 파일 형식만 확인하고 허용에 넣어뒀습니다.

2021-12-14 05:54 UTC, wherehows commented
에러 문구가 반응형에서 끝까지 늘어나지 않는 것 같아서요! 가로를 꽉채우게 늘리는건 어떨까용?
![image](https://user-images.githubusercontent.com/81841082/145941135-5f1b77f4-3174-46d3-b562-2e7e468e2373.png)

2021-12-14 05:54 UTC, wherehows approved these changes

2021-12-14 07:37 UTC, merged