Feat: MyPostPage 마크업 추가
prgrms-web-devcourse/Team_i6_comepet_FE pull request #81
Opened 2021-12-13 18:42 UTC by Jihyeon228

## 이슈 번호 

- close: Feat: MyPostPage 마크업 추가 #80

2021-12-14 05:56 UTC, wherehows approved these changes

2021-12-14 05:59 UTC, sanoopark commented on src/views/User/MyPostPage/MyPostPage.jsx
> +  justify-content: space-between;
```suggestion
  justify-content: center;
```

![image](https://user-images.githubusercontent.com/81365896/145941301-e19e143a-d530-4ba5-b951-64c79d668254.png)

![image](https://user-images.githubusercontent.com/81365896/145941356-572bdd04-c2f2-4d55-8651-cc3d153b0c3a.png)

space-between으로 하면 반응형에서 비어 있는 지점이 있네요

2021-12-14 06:00 UTC, sanoopark commented on src/views/User/MyPostPage/MyPostPage.jsx
> +  const postLength = 0;
```suggestion
  const postLength = posts.length;
```

테스트용인 것 같은데 서버 데이터를 가져와도 위와 같은 형태가 될 것 같아요

2021-12-14 06:00 UTC, sanoopark requested changes
코멘트 드렸습니다!

2021-12-14 07:06 UTC, Jihyeon228 commented on src/views/User/MyPostPage/MyPostPage.jsx
> +  justify-content: space-between;
게시글이 홀수일 때 이렇게 나와서 수정한 건데 center가 더 낫겠네요.
<img width="342" alt="image" src="https://user-images.githubusercontent.com/75232366/145949372-9d4bbbbf-06a6-4cf5-8d64-74f62b1e7e75.png">

2021-12-15 05:50 UTC, sanoopark approved these changes

2021-12-15 06:14 UTC, merged